"""changing column names

Revision ID: 523563dc1e4f
Revises: 6e22b9a7f979
Create Date: 2025-05-05 05:23:22.584809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "523563dc1e4f"
down_revision: Union[str, None] = "6e22b9a7f979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(), nullable=False))
    op.drop_index("ix_users_email", table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.VARCHAR(), nullable=False))
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(), nullable=False))
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=1)
    op.drop_column("users", "password")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
